### PR TITLE
acceptAll

### PR DESCRIPTION
**Pull request by yaki3355**
#7

### CODE REVIEW

**Comment by ingomohr** [comment]
Thank you @yaki3355 for the contribution! :)

Looks good.

Two small things:
* Could you add a jdoc comment to the method? (💡 you can check with the other public methods in that class)
* If it's no trouble for you: Could you add a unit test that proves the impl is right? (#7 has an acceptance criterium for this).
    * 💡If you're not familiar w/ JUnit, you can just say so and I'll add the test myself.

**Comment by yaki3355** [comment]
Hey @ingomohr
I hope it's ok now..

**Comment by ingomohr** [comment]
Thank you @yaki3355!

**Comment by yaki3355** [comment]
> Thank you @yaki3355!

👍

**Pull request merged**
